# NOTE: settings in this file have precedence over settings on the website
image: Visual Studio 2013

matrix:
  fast_finish: true

platform:
#  - Win32
  - x64

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

configuration:
  - Debug
#  - Release

environment:
  matrix:
    - TOOLCHAIN_VERSION: 12.0
      solution_name: win_build\boinc_vs2013.sln
      depends_git_path: http://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git
      depends_path: C:\projects\boinc_depends_win_vs2013

cache:
  - C:\projects\boinc_depends_win_vs2013

before_build:
  - call win_build\load_dependencies.bat %depends_git_path% %depends_path% %platform% %configuration%
  - if %TOOLCHAIN_VERSION%==12.0 call "%VS120COMNTOOLS%\vsvars32.bat"

build_script:
  - devenv %solution_name% /Build "%configuration%|%platform%"

build:
  parallel: true
  verbosity: minimal

test: off
