# This file is part of BOINC.
# https://boinc.berkeley.edu
# Copyright (C) 2025 University of California
#
# BOINC is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# BOINC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with BOINC.  If not, see <http://www.gnu.org/licenses/>.

name: Android
on:
  push:
    branches: [ master, 'client_release/**' ]
    tags: [ 'client_release/**' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build-client:
    name: client-${{ matrix.type }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [armv6, arm, arm64, x86, x86_64]
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libncurses6

      - name: Fix libncurses5 missing for armv6
        if: ${{ success() && matrix.type == 'armv6' }}
        run: |
          sudo ln -s /lib/x86_64-linux-gnu/libncurses.so.6 /lib/x86_64-linux-gnu/libncurses.so.5
          sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5

      - name: Check if build is running from origin repo
        if: ${{ success() && env.AWS_ACCESS_KEY_ID != 0 && env.AWS_SECRET_ACCESS_KEY != 0 }}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws,s3://vcpkg.cache.boinc/,readwrite" >> $GITHUB_ENV

      - name: Check if build is running from fork
        if: ${{ success() && (env.AWS_ACCESS_KEY_ID == 0 || env.AWS_SECRET_ACCESS_KEY == 0) }}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws-config,no-sign-request;x-aws,s3://vcpkg.cache.boinc/,read" >> $GITHUB_ENV

      - name: Unset ANDROID_NDK_ROOT environment variable
        if: ${{ success() }}
        run: |
          echo ANDROID_NDK_ROOT="" >> $GITHUB_ENV

      - name: Build client with vcpkg
        if: ${{ success() }}
        run: ./android/ci_build_vcpkg_client.sh --arch ${{ matrix.type }}

      - name: Prepare logs on failure
        if: ${{ failure() }}
        run: python ./deploy/prepare_deployment.py logs

      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: android_logs_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
          path: deploy/logs.7z

      - name: Upload client on success
        if: ${{ success() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: android_client_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
          path: android/BOINC/app/src/main/assets/

  build-manager:
    name: manager-build
    runs-on: ubuntu-latest
    needs: build-client
    strategy:
      matrix:
        task: [assembleRelease, assembleArmv6_release, jacocoTestReportDebug]
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 2

      - name: Download armv6 client
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          name: android_client_armv6_${{ github.event.pull_request.head.sha }}
          path: android/BOINC/app/src/main/assets/

      - name: Download arm client
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          name: android_client_arm_${{ github.event.pull_request.head.sha }}
          path: android/BOINC/app/src/main/assets/

      - name: Download arm64 client
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          name: android_client_arm64_${{ github.event.pull_request.head.sha }}
          path: android/BOINC/app/src/main/assets/

      - name: Download x86 client
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          name: android_client_x86_${{ github.event.pull_request.head.sha }}
          path: android/BOINC/app/src/main/assets/

      - name: Download x86_64 client
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          name: android_client_x86_64_${{ github.event.pull_request.head.sha }}
          path: android/BOINC/app/src/main/assets/

      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: 'zulu'
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407

      - name: Build manager with vcpkg
        run: ./android/ci_build_vcpkg_manager.sh --skip-client-build --tasks "clean ${{ matrix.task }}"

      - name: Prepare logs on failure
        if: ${{ failure() }}
        run: python ./deploy/prepare_deployment.py logs

      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: android_logs_manager_${{ github.event.pull_request.head.sha }}
          path: deploy/logs.7z

      - name: Upload generic artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        if: ${{ matrix.task == 'assembleRelease' }}
        with:
          name: android_manager_${{ github.event.pull_request.head.sha }}
          path: android/BOINC/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload armv6 only manager
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        if: ${{ matrix.task == 'assembleArmv6_release' }}
        with:
          name: android_armv6_manager_${{ github.event.pull_request.head.sha }}
          path: android/BOINC/app/build/outputs/apk/armv6_release/app-armv6_release-unsigned.apk

      - name: Upload JUnit Tests Results
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        if: ${{ always() && matrix.task == 'jacocoTestReportDebug' }}
        with:
          name: Android_tests_results
          path: android/BOINC/app/build/test-results/testDebugUnitTest/TEST-*.xml

      - name: Upload coverage report
        if: ${{ matrix.task == 'jacocoTestReportDebug' }}
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: ${{ matrix.type }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [libs, apps, libs-cmake]
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libncurses6

      - name: Fix libncurses5 missing for armv6
        if : ${{ success() }}
        run: |
          sudo ln -s /lib/x86_64-linux-gnu/libncurses.so.6 /lib/x86_64-linux-gnu/libncurses.so.5
          sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5

      - name: Check if build is running from origin repo
        if: ${{ success() && env.AWS_ACCESS_KEY_ID != 0 && env.AWS_SECRET_ACCESS_KEY != 0 }}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws,s3://vcpkg.cache.boinc/,readwrite" >> $GITHUB_ENV

      - name: Check if build is running from fork
        if: ${{ success() && (env.AWS_ACCESS_KEY_ID == 0 || env.AWS_SECRET_ACCESS_KEY == 0) }}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws-config,no-sign-request;x-aws,s3://vcpkg.cache.boinc/,read" >> $GITHUB_ENV

      - name: Unset ANDROID_NDK_ROOT environment variable
        if: ${{ success() }}
        run: |
          echo ANDROID_NDK_ROOT="" >> $GITHUB_ENV

      - name: Build libs with vcpkg
        if: ${{ success() && matrix.type == 'libs' }}
        run: ./android/ci_build_vcpkg_libraries.sh

      - name: Build apps with vcpkg
        if: ${{ success() && matrix.type == 'apps' }}
        run: ./android/ci_build_vcpkg_apps.sh

      - name: Build libs with cmake
        if: ${{ success() && matrix.type == 'libs-cmake' }}
        run: ./android/ci_build_libs_cmake.sh

      - name: Prepare logs on failure
        if: ${{ failure() }}
        run: python ./deploy/prepare_deployment.py logs

      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: android_logs_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
          path: deploy/logs.7z

      - name: Prepare artifacts for deploy
        if: ${{ success() && matrix.type == 'apps' }}
        run: python ./deploy/prepare_deployment.py android_${{ matrix.type }}

      - name: Upload generic artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        if: ${{ success() && matrix.type == 'apps' }}
        with:
          name: android_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
          path: deploy/android_${{ matrix.type }}.7z
