name: Maintenance
on:
  schedule:
    - cron:  '0 15 * * 0'

jobs:
  build:
    name: ${{ matrix.type }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [maintenance]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Configure Python
        run: |
          pip install boto3==1.19.12

      - name: Cleanup outdated binary cache
        if: ${{ success() }}
        env:
          ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          python ./deploy/cleanup_vcpkg_archive_cache.py ./vcpkgcache "edu.berkeley.boinc.github.actions.build.vcpkg.binary.cache" "$ACCESS_KEY" "$SECRET_KEY"
