name: Source Code Check
on:
  push:
    branches: [ master, 'client_release/**' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '25 12 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.type }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [source-code-check]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check source code for illegal symbols
        if: ${{ success() }}
        run: |
          python ./ci_tools/source_code_check.py .
      - name: Check source code for trailing whitespaces
        if: ${{ success() }}
        run: |
          python ./ci_tools/trailing_whitespaces_check.py .
